In [1]:
import wandb
from wandb.integration.keras import WandbMetricsLogger

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras

In [2]:
sweep_config = {

    'method'   : 'grid',
    'metric'   : {
        'name' : 'val_accuracy',
        'goal' : 'maximize'
                 },
    'parameters' : {
        'batch_size'    : {'values': [8,16]},
        'learning_rate' : {'values': [0.001,0.0001]},
        'hidden_nodes'  : {'values': [128,64]},
        'img_size'      : {'values': [16, 224]},
        'epochs'        : {'values': [5,10]}
    }
}

sweep_id = wandb.sweep(sweep_config, project="5-flowers-classification")

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:

 2

wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.
wandb: Paste your API key and hit enter:

 ··········

wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

Create sweep with ID: 472kegn8
Sweep URL: https://wandb.ai/jaicky-iit-ism-dhanbad/5-flowers-classification/sweeps/472kegn8

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kausthubkannan/5-flower-types-classification-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/kausthubkannan/5-flower-types-classification-dataset/1.archive...

100%|██████████| 242M/242M [00:01<00:00, 182MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/kausthubkannan/5-flower-types-classification-dataset/versions/1

In [4]:
import os
print(os.listdir(path))
new_path = os.path.join(path, "flower_images")
print(os.listdir(new_path))

['flower_images']
['Tulip', 'Lilly', 'Orchid', 'Lotus', 'Sunflower']

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
import os

image_paths = []
labels = []

# Define CLASS_NAMES here so it's accessible
CLASS_NAMES = ['Lilly', 'Tulip', 'Sunflower', 'Lotus', 'Orchid']

# 'new_path' is already defined from cell ODzq1vCHVNVj
# 'CLASS_NAMES' is already defined from cell WFuC9l3YS4vl

# Populate image_paths and labels
for class_name in CLASS_NAMES:
    class_dir = os.path.join(new_path, class_name)
    if os.path.exists(class_dir):
        for img_name in os.listdir(class_dir):
            if img_name.lower().endswith(('.png', '.jpg', '.jpeg')):
                image_paths.append(os.path.join(class_dir, img_name))
                labels.append(class_name)

if not image_paths:
    print("No image files found. Please verify the dataset structure and 'new_path'.")
else:
    df = pd.DataFrame({'filename': image_paths, 'label': labels})

    # Split into training and evaluation sets
    train_df, eval_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

    # Save to CSV files in the current working directory
    train_csv_path = 'train_set.csv'
    eval_csv_path = 'eval_set.csv'
    train_df.to_csv(train_csv_path, index=False, header=False)
    eval_df.to_csv(eval_csv_path, index=False, header=False)

    print(f"Generated training CSV: {train_csv_path} ({len(train_df)} samples)")
    print(f"Generated evaluation CSV: {eval_csv_path} ({len(eval_df)} samples)")

    print("\nTrain DataFrame Head:")
    display(train_df.head())
    print("\nEval DataFrame Head:")
    display(eval_df.head())

Generated training CSV: train_set.csv (3999 samples)
Generated evaluation CSV: eval_set.csv (1000 samples)

Train DataFrame Head:

                                               filename      label
3173  /root/.cache/kagglehub/datasets/kausthubkannan...      Lotus
1215  /root/.cache/kagglehub/datasets/kausthubkannan...      Tulip
1914  /root/.cache/kagglehub/datasets/kausthubkannan...      Tulip
2417  /root/.cache/kagglehub/datasets/kausthubkannan...  Sunflower
193   /root/.cache/kagglehub/datasets/kausthubkannan...      Lilly

Eval DataFrame Head:

                                               filename      label
3446  /root/.cache/kagglehub/datasets/kausthubkannan...      Lotus
2502  /root/.cache/kagglehub/datasets/kausthubkannan...  Sunflower
955   /root/.cache/kagglehub/datasets/kausthubkannan...      Lilly
4880  /root/.cache/kagglehub/datasets/kausthubkannan...     Orchid
4617  /root/.cache/kagglehub/datasets/kausthubkannan...     Orchid

In [6]:
def train():
  with wandb.init() as run:
    config = wandb.config

    # Constants
    IMG_HEIGHT = config.img_size
    IMG_WIDTH = config.img_size
    IMG_CHANNELS = 3
    CLASS_NAMES = ['Lilly', 'Tulip', 'Sunflower', 'Lotus', 'Orchid']



    def read_and_decode(filename, resize_dims):
        img_bytes = tf.io.read_file(filename)
        img = tf.image.decode_jpeg(img_bytes, channels=IMG_CHANNELS)
        img = tf.image.convert_image_dtype(img, tf.float32)
        img = tf.image.resize(img, resize_dims)
        return img

    def parse_csvline(csv_line):
        record_default = ["", ""]
        filename, label_string = tf.io.decode_csv(csv_line, record_default)

        img = read_and_decode(filename, [IMG_HEIGHT, IMG_WIDTH])

        # Convert label string to an integer index
        label = tf.where(tf.equal(CLASS_NAMES, label_string))[0, 0]

        return img, label

    # Define datasets
    train_dataset = (
        tf.data.TextLineDataset(os.path.join(os.getcwd(), train_csv_path))
        .skip(1) # Skip header if present, but we generated without header
        .map(parse_csvline, num_parallel_calls=tf.data.AUTOTUNE)
        .batch(config.batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )

    eval_dataset = (
        tf.data.TextLineDataset(os.path.join(os.getcwd(), eval_csv_path))
        .skip(1) # Skip header if present, but we generated without header
        .map(parse_csvline, num_parallel_calls=tf.data.AUTOTUNE)
        .batch(config.batch_size)
        .prefetch(tf.data.AUTOTUNE)
    )


    #architecture
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS)),
        keras.layers.Dense(config.hidden_nodes, activation="relu"),
        keras.layers.Dense(len(CLASS_NAMES), activation="softmax")
    ])

    model.compile(
          optimizer=keras.optimizers.Adam(learning_rate=config.learning_rate),
          loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
          metrics=["accuracy"]
      )

    model.fit(
      train_dataset,
      validation_data=eval_dataset,
      epochs=config.epochs,
      callbacks=[WandbMetricsLogger(log_freq=5)]
      )

In [7]:
wandb.agent(sweep_id, function=train)

wandb: Agent Starting Run: nsku5rpx with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: jaikeeanand007 (jaicky-iit-ism-dhanbad) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/5
    500/Unknown 13s 23ms/step - accuracy: 0.3537 - loss: 1.5352

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 31ms/step - accuracy: 0.4082 - loss: 1.4218 - val_accuracy: 0.4655 - val_loss: 1.3067
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 37ms/step - accuracy: 0.4817 - loss: 1.2496 - val_accuracy: 0.4735 - val_loss: 1.2409
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 32s 64ms/step - accuracy: 0.5105 - loss: 1.1989 - val_accuracy: 0.5105 - val_loss: 1.2003
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5318 - loss: 1.1367 - val_accuracy: 0.5105 - val_loss: 1.1764
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5625 - loss: 1.0893 - val_accuracy: 0.5055 - val_loss: 1.1712

wandb: Agent Starting Run: halpmcjc with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 30ms/step - accuracy: 0.3647 - loss: 1.4668 - val_accuracy: 0.4154 - val_loss: 1.3693
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.4607 - loss: 1.3008 - val_accuracy: 0.4274 - val_loss: 1.3162
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.4922 - loss: 1.2399 - val_accuracy: 0.4384 - val_loss: 1.2894
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5115 - loss: 1.1981 - val_accuracy: 0.4585 - val_loss: 1.2622
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5263 - loss: 1.1665 - val_accuracy: 0.4595 - val_loss: 1.2475

wandb: Agent Starting Run: 0kgds8a0 with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 36ms/step - accuracy: 0.2911 - loss: 13.7532 - val_accuracy: 0.2012 - val_loss: 1.6086
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.1996 - loss: 1.6041 - val_accuracy: 0.2533 - val_loss: 1.6126
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2104 - loss: 1.5992 - val_accuracy: 0.2052 - val_loss: 1.6042
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.2076 - loss: 1.6031 - val_accuracy: 0.2693 - val_loss: 1.7178
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.2151 - loss: 1.5958 - val_accuracy: 0.2022 - val_loss: 1.6080

wandb: Agent Starting Run: zkgky7qg with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 34ms/step - accuracy: 0.3677 - loss: 2.6231 - val_accuracy: 0.4505 - val_loss: 1.3877
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - accuracy: 0.4457 - loss: 1.7115 - val_accuracy: 0.4274 - val_loss: 1.8792
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.4675 - loss: 1.5555 - val_accuracy: 0.4204 - val_loss: 1.4416
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.4802 - loss: 1.3799 - val_accuracy: 0.4555 - val_loss: 1.4287
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.5115 - loss: 1.2750 - val_accuracy: 0.4384 - val_loss: 1.4505

wandb: Agent Starting Run: g7tg6e3l with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 31ms/step - accuracy: 0.3994 - loss: 1.4165 - val_accuracy: 0.4635 - val_loss: 1.3014
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 29ms/step - accuracy: 0.4757 - loss: 1.2556 - val_accuracy: 0.4785 - val_loss: 1.2607
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 38ms/step - accuracy: 0.4980 - loss: 1.2045 - val_accuracy: 0.4875 - val_loss: 1.2260
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5300 - loss: 1.1496 - val_accuracy: 0.4965 - val_loss: 1.2037
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5548 - loss: 1.1040 - val_accuracy: 0.5135 - val_loss: 1.1803

wandb: Agent Starting Run: 78w5k4ak with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 30ms/step - accuracy: 0.3407 - loss: 1.4902 - val_accuracy: 0.4244 - val_loss: 1.3885
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 28ms/step - accuracy: 0.4325 - loss: 1.3547 - val_accuracy: 0.4755 - val_loss: 1.3137
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 28ms/step - accuracy: 0.4652 - loss: 1.2860 - val_accuracy: 0.4775 - val_loss: 1.2750
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.4917 - loss: 1.2419 - val_accuracy: 0.4825 - val_loss: 1.2463
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5048 - loss: 1.2078 - val_accuracy: 0.5095 - val_loss: 1.2288

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: o8lx47ek with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 35ms/step - accuracy: 0.3199 - loss: 15.3352 - val_accuracy: 0.3514 - val_loss: 5.5115
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2549 - loss: 1.6277 - val_accuracy: 0.2022 - val_loss: 1.6447
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2099 - loss: 1.5912 - val_accuracy: 0.2042 - val_loss: 1.5854
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - accuracy: 0.2464 - loss: 1.5651 - val_accuracy: 0.2012 - val_loss: 1.6107
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.2211 - loss: 1.5912 - val_accuracy: 0.2773 - val_loss: 1.5042

wandb: Agent Starting Run: pssmm9na with config:
wandb: 	batch_size: 8
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - accuracy: 0.3699 - loss: 2.4268 - val_accuracy: 0.3964 - val_loss: 1.9837
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.4512 - loss: 1.7398 - val_accuracy: 0.4144 - val_loss: 1.8491
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.5028 - loss: 1.4878 - val_accuracy: 0.4605 - val_loss: 1.8440
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.5350 - loss: 1.3585 - val_accuracy: 0.4484 - val_loss: 1.9356
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.5650 - loss: 1.3296 - val_accuracy: 0.4785 - val_loss: 1.7403

wandb: Agent Starting Run: dmc1e58o with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 29ms/step - accuracy: 0.4110 - loss: 1.4220 - val_accuracy: 0.4635 - val_loss: 1.3127
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 28ms/step - accuracy: 0.4747 - loss: 1.2614 - val_accuracy: 0.4645 - val_loss: 1.2700
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 32s 63ms/step - accuracy: 0.5110 - loss: 1.2000 - val_accuracy: 0.5005 - val_loss: 1.1833
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5313 - loss: 1.1424 - val_accuracy: 0.4855 - val_loss: 1.2035
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5640 - loss: 1.0938 - val_accuracy: 0.4975 - val_loss: 1.1771
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5803 - loss: 1.0505 - val_accuracy: 0.5215 - val_loss: 1.1454
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 49s 98ms/step - accuracy: 0.6048 - loss: 0.9976 - val_accuracy: 0.5205 - val_loss: 1.1355
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.6181 - loss: 0.9695 - val_accuracy: 0.5425 - val_loss: 1.1316
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.6446 - loss: 0.9188 - val_accuracy: 0.5465 - val_loss: 1.1271
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.6621 - loss: 0.8866 - val_accuracy: 0.5656 - val_loss: 1.1334

wandb: Agent Starting Run: rrv4tocf with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 30ms/step - accuracy: 0.3939 - loss: 1.4188 - val_accuracy: 0.4414 - val_loss: 1.3207
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.4715 - loss: 1.2839 - val_accuracy: 0.4585 - val_loss: 1.2656
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.4980 - loss: 1.2283 - val_accuracy: 0.4805 - val_loss: 1.2344
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5203 - loss: 1.1886 - val_accuracy: 0.4685 - val_loss: 1.2245
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5398 - loss: 1.1585 - val_accuracy: 0.4945 - val_loss: 1.2044
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 51s 103ms/step - accuracy: 0.5535 - loss: 1.1299 - val_accuracy: 0.4985 - val_loss: 1.1919
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5633 - loss: 1.1031 - val_accuracy: 0.5085 - val_loss: 1.1813
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5818 - loss: 1.0781 - val_accuracy: 0.5195 - val_loss: 1.1699
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5948 - loss: 1.0562 - val_accuracy: 0.5245 - val_loss: 1.1624
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.6096 - loss: 1.0325 - val_accuracy: 0.5315 - val_loss: 1.1545

wandb: Agent Starting Run: ldc7ti3y with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 33ms/step - accuracy: 0.3172 - loss: 13.3508 - val_accuracy: 0.2452 - val_loss: 1.6103
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 32ms/step - accuracy: 0.2319 - loss: 1.5991 - val_accuracy: 0.2933 - val_loss: 1.5775
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2416 - loss: 1.5752 - val_accuracy: 0.2322 - val_loss: 1.6063
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2264 - loss: 1.5901 - val_accuracy: 0.2402 - val_loss: 1.5726
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 35ms/step - accuracy: 0.2476 - loss: 1.5713 - val_accuracy: 0.2713 - val_loss: 1.5651
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2444 - loss: 1.5790 - val_accuracy: 0.2613 - val_loss: 1.6120
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2216 - loss: 1.5958 - val_accuracy: 0.2563 - val_loss: 1.6443
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2566 - loss: 1.5640 - val_accuracy: 0.2803 - val_loss: 1.6012
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2379 - loss: 1.5844 - val_accuracy: 0.2332 - val_loss: 1.6101
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.2089 - loss: 1.6021 - val_accuracy: 0.2603 - val_loss: 1.6602

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: evnqlzby with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 33ms/step - accuracy: 0.3792 - loss: 3.6060 - val_accuracy: 0.3664 - val_loss: 2.4345
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.4362 - loss: 2.2103 - val_accuracy: 0.3844 - val_loss: 3.0076
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.4932 - loss: 1.7954 - val_accuracy: 0.4384 - val_loss: 3.6470
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.5308 - loss: 1.6079 - val_accuracy: 0.5025 - val_loss: 2.0444
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - accuracy: 0.5365 - loss: 1.5396 - val_accuracy: 0.4054 - val_loss: 3.4764
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.5733 - loss: 1.4518 - val_accuracy: 0.3994 - val_loss: 3.2449
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.5813 - loss: 1.4693 - val_accuracy: 0.4254 - val_loss: 2.6431
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - accuracy: 0.5930 - loss: 1.3473 - val_accuracy: 0.4084 - val_loss: 2.6330
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 33ms/step - accuracy: 0.6233 - loss: 1.2589 - val_accuracy: 0.3724 - val_loss: 3.6486
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 21s 43ms/step - accuracy: 0.6096 - loss: 1.3269 - val_accuracy: 0.4625 - val_loss: 1.7593

wandb: Agent Starting Run: xx2uwkra with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 32ms/step - accuracy: 0.4097 - loss: 1.3939 - val_accuracy: 0.4695 - val_loss: 1.3089
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 29ms/step - accuracy: 0.4695 - loss: 1.2488 - val_accuracy: 0.4645 - val_loss: 1.3172
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.4990 - loss: 1.1931 - val_accuracy: 0.4575 - val_loss: 1.2922
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5303 - loss: 1.1418 - val_accuracy: 0.4725 - val_loss: 1.2475
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5530 - loss: 1.1000 - val_accuracy: 0.4925 - val_loss: 1.2091
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5765 - loss: 1.0557 - val_accuracy: 0.5055 - val_loss: 1.2031
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5905 - loss: 1.0144 - val_accuracy: 0.5085 - val_loss: 1.2042
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.6166 - loss: 0.9767 - val_accuracy: 0.5285 - val_loss: 1.1848
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.6353 - loss: 0.9397 - val_accuracy: 0.5415 - val_loss: 1.1910
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 29ms/step - accuracy: 0.6556 - loss: 0.9003 - val_accuracy: 0.5395 - val_loss: 1.1855

wandb: Agent Starting Run: tz49g4v6 with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.3387 - loss: 1.5151 - val_accuracy: 0.4194 - val_loss: 1.3865
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.4357 - loss: 1.3479 - val_accuracy: 0.4575 - val_loss: 1.3167
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.4682 - loss: 1.2844 - val_accuracy: 0.4805 - val_loss: 1.2816
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.4920 - loss: 1.2427 - val_accuracy: 0.4945 - val_loss: 1.2594
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5028 - loss: 1.2112 - val_accuracy: 0.5055 - val_loss: 1.2390
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5223 - loss: 1.1836 - val_accuracy: 0.5045 - val_loss: 1.2253
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 30ms/step - accuracy: 0.5340 - loss: 1.1603 - val_accuracy: 0.5165 - val_loss: 1.2151
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5435 - loss: 1.1388 - val_accuracy: 0.5205 - val_loss: 1.2038
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 28ms/step - accuracy: 0.5590 - loss: 1.1184 - val_accuracy: 0.5235 - val_loss: 1.1962
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 14s 29ms/step - accuracy: 0.5650 - loss: 1.0994 - val_accuracy: 0.5305 - val_loss: 1.1879

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 57hhky8q with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 34ms/step - accuracy: 0.2034 - loss: 4.9350 - val_accuracy: 0.1992 - val_loss: 1.6095
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 33ms/step - accuracy: 0.1968 - loss: 1.6097 - val_accuracy: 0.1992 - val_loss: 1.6095
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 40ms/step - accuracy: 0.1911 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.1936 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.1931 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.1913 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 82s 164ms/step - accuracy: 0.1921 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.1923 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.1913 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.1916 - loss: 1.6097 - val_accuracy: 0.2002 - val_loss: 1.6095

wandb: Agent Starting Run: hwxhx01f with config:
wandb: 	batch_size: 8
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 34ms/step - accuracy: 0.3657 - loss: 2.2334 - val_accuracy: 0.4114 - val_loss: 1.5856
Epoch 2/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.4315 - loss: 1.6550 - val_accuracy: 0.2142 - val_loss: 1.6375
Epoch 3/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.3649 - loss: 1.4474 - val_accuracy: 0.3784 - val_loss: 1.5078
Epoch 4/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.4117 - loss: 1.4102 - val_accuracy: 0.4294 - val_loss: 1.4196
Epoch 5/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.4207 - loss: 1.3784 - val_accuracy: 0.4384 - val_loss: 1.3808
Epoch 6/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - accuracy: 0.4075 - loss: 1.3672 - val_accuracy: 0.2853 - val_loss: 1.5469
Epoch 7/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - accuracy: 0.2809 - loss: 1.5208 - val_accuracy: 0.2833 - val_loss: 1.5430
Epoch 8/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2904 - loss: 1.5068 - val_accuracy: 0.2923 - val_loss: 1.5317
Epoch 9/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 33ms/step - accuracy: 0.2831 - loss: 1.5127 - val_accuracy: 0.2883 - val_loss: 1.5575
Epoch 10/10
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.2859 - loss: 1.5051 - val_accuracy: 0.2833 - val_loss: 1.5342

wandb: Agent Starting Run: q0nvnyc4 with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - accuracy: 0.4002 - loss: 1.4076 - val_accuracy: 0.4134 - val_loss: 1.3306
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - accuracy: 0.4820 - loss: 1.2417 - val_accuracy: 0.4324 - val_loss: 1.3083
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5183 - loss: 1.1764 - val_accuracy: 0.4755 - val_loss: 1.2255
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5468 - loss: 1.1231 - val_accuracy: 0.5005 - val_loss: 1.1958
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5665 - loss: 1.0736 - val_accuracy: 0.5185 - val_loss: 1.1850

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: yz039xfc with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 65ms/step - accuracy: 0.3354 - loss: 1.5125 - val_accuracy: 0.4254 - val_loss: 1.3871
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - accuracy: 0.4450 - loss: 1.3397 - val_accuracy: 0.4665 - val_loss: 1.3114
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - accuracy: 0.4800 - loss: 1.2704 - val_accuracy: 0.4805 - val_loss: 1.2713
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - accuracy: 0.4972 - loss: 1.2258 - val_accuracy: 0.4865 - val_loss: 1.2450
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 78ms/step - accuracy: 0.5130 - loss: 1.1933 - val_accuracy: 0.4905 - val_loss: 1.2247

wandb: Agent Starting Run: 3xdiz85x with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 68ms/step - accuracy: 0.3424 - loss: 12.2341 - val_accuracy: 0.4254 - val_loss: 7.2236
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - accuracy: 0.4362 - loss: 4.3804 - val_accuracy: 0.3293 - val_loss: 7.0844
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.4402 - loss: 4.5772 - val_accuracy: 0.2402 - val_loss: 8.0703
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.3399 - loss: 2.1142 - val_accuracy: 0.3924 - val_loss: 1.4532
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 48s 193ms/step - accuracy: 0.3477 - loss: 1.4763 - val_accuracy: 0.2503 - val_loss: 1.5703

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: i4gbc641 with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 72ms/step - accuracy: 0.3852 - loss: 2.1191 - val_accuracy: 0.3433 - val_loss: 2.4561
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 66ms/step - accuracy: 0.4467 - loss: 1.5408 - val_accuracy: 0.4064 - val_loss: 2.1747
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.4917 - loss: 1.3684 - val_accuracy: 0.4204 - val_loss: 1.5991
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - accuracy: 0.5230 - loss: 1.2388 - val_accuracy: 0.4394 - val_loss: 1.5162
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.5360 - loss: 1.2425 - val_accuracy: 0.5095 - val_loss: 1.2472

wandb: Agent Starting Run: rc6xw7q4 with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - accuracy: 0.3902 - loss: 1.4308 - val_accuracy: 0.4615 - val_loss: 1.3059
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.4795 - loss: 1.2651 - val_accuracy: 0.4865 - val_loss: 1.2674
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5048 - loss: 1.2102 - val_accuracy: 0.5015 - val_loss: 1.2428
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5288 - loss: 1.1637 - val_accuracy: 0.5115 - val_loss: 1.2283
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5438 - loss: 1.1309 - val_accuracy: 0.5315 - val_loss: 1.2000

wandb: Agent Starting Run: h8i83b2a with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 61ms/step - accuracy: 0.3439 - loss: 1.4974 - val_accuracy: 0.4004 - val_loss: 1.3997
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 57ms/step - accuracy: 0.4362 - loss: 1.3489 - val_accuracy: 0.4354 - val_loss: 1.3286
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - accuracy: 0.4685 - loss: 1.2906 - val_accuracy: 0.4605 - val_loss: 1.2920
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.4860 - loss: 1.2533 - val_accuracy: 0.4735 - val_loss: 1.2689
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.4932 - loss: 1.2269 - val_accuracy: 0.4785 - val_loss: 1.2540

wandb: Agent Starting Run: dnd3q6zi with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 69ms/step - accuracy: 0.3232 - loss: 14.4562 - val_accuracy: 0.2342 - val_loss: 14.2711
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.3902 - loss: 5.0723 - val_accuracy: 0.2122 - val_loss: 1.6018
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.2346 - loss: 1.5853 - val_accuracy: 0.2813 - val_loss: 1.5737
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.2594 - loss: 1.5714 - val_accuracy: 0.3093 - val_loss: 1.5781
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 78ms/step - accuracy: 0.2569 - loss: 1.5608 - val_accuracy: 0.3113 - val_loss: 1.5654

wandb: Agent Starting Run: gzca7maw with config:
wandb: 	batch_size: 16
wandb: 	epochs: 5
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 67ms/step - accuracy: 0.3632 - loss: 2.1593 - val_accuracy: 0.3774 - val_loss: 1.5534
Epoch 2/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 65ms/step - accuracy: 0.3657 - loss: 1.4540 - val_accuracy: 0.4084 - val_loss: 1.4217
Epoch 3/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 66ms/step - accuracy: 0.3717 - loss: 1.4525 - val_accuracy: 0.3524 - val_loss: 1.4414
Epoch 4/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.3807 - loss: 1.4137 - val_accuracy: 0.4334 - val_loss: 1.3840
Epoch 5/5
250/250 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - accuracy: 0.3942 - loss: 1.4103 - val_accuracy: 0.4024 - val_loss: 1.3921

wandb: Agent Starting Run: ex9tgtie with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 62ms/step - accuracy: 0.4107 - loss: 1.3899 - val_accuracy: 0.4454 - val_loss: 1.3034
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.4820 - loss: 1.2451 - val_accuracy: 0.4805 - val_loss: 1.2550
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5170 - loss: 1.1767 - val_accuracy: 0.5085 - val_loss: 1.2163
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5353 - loss: 1.1342 - val_accuracy: 0.4645 - val_loss: 1.2715
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5618 - loss: 1.0957 - val_accuracy: 0.5255 - val_loss: 1.2146
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5860 - loss: 1.0434 - val_accuracy: 0.5335 - val_loss: 1.1917
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.6123 - loss: 0.9961 - val_accuracy: 0.5365 - val_loss: 1.1844
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.6343 - loss: 0.9588 - val_accuracy: 0.5616 - val_loss: 1.1669
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 81s 324ms/step - accuracy: 0.6493 - loss: 0.9198 - val_accuracy: 0.5796 - val_loss: 1.0964
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.6611 - loss: 0.8833 - val_accuracy: 0.5686 - val_loss: 1.1366

wandb: Agent Starting Run: y4iuow6s with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.3527 - loss: 1.4847 - val_accuracy: 0.4254 - val_loss: 1.3771
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - accuracy: 0.4542 - loss: 1.3301 - val_accuracy: 0.4494 - val_loss: 1.3135
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.4887 - loss: 1.2677 - val_accuracy: 0.4825 - val_loss: 1.2780
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5093 - loss: 1.2258 - val_accuracy: 0.5005 - val_loss: 1.2523
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 49s 195ms/step - accuracy: 0.5250 - loss: 1.1923 - val_accuracy: 0.5125 - val_loss: 1.2334
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5353 - loss: 1.1645 - val_accuracy: 0.5205 - val_loss: 1.2180
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5443 - loss: 1.1409 - val_accuracy: 0.5285 - val_loss: 1.2062
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5585 - loss: 1.1194 - val_accuracy: 0.5275 - val_loss: 1.1944
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 47s 189ms/step - accuracy: 0.5675 - loss: 1.0987 - val_accuracy: 0.5235 - val_loss: 1.1848
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5808 - loss: 1.0793 - val_accuracy: 0.5295 - val_loss: 1.1761

wandb: Agent Starting Run: 8u8hwq8o with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 66ms/step - accuracy: 0.3639 - loss: 11.4764 - val_accuracy: 0.3824 - val_loss: 4.9204
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 66ms/step - accuracy: 0.4357 - loss: 4.2951 - val_accuracy: 0.3804 - val_loss: 5.7367
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 66ms/step - accuracy: 0.4545 - loss: 2.9344 - val_accuracy: 0.4454 - val_loss: 3.4487
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 65ms/step - accuracy: 0.4627 - loss: 2.4463 - val_accuracy: 0.1481 - val_loss: 1.6046
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - accuracy: 0.1983 - loss: 1.5734 - val_accuracy: 0.3203 - val_loss: 1.6756
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.2981 - loss: 1.5574 - val_accuracy: 0.2653 - val_loss: 1.5778
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 83s 335ms/step - accuracy: 0.2894 - loss: 1.5490 - val_accuracy: 0.2553 - val_loss: 1.5753
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.2951 - loss: 1.5334 - val_accuracy: 0.3033 - val_loss: 1.5359
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.2819 - loss: 1.5402 - val_accuracy: 0.3453 - val_loss: 1.4992
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - accuracy: 0.2876 - loss: 1.5356 - val_accuracy: 0.2983 - val_loss: 1.5228

wandb: Agent Starting Run: n43op1cb with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 128
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 70ms/step - accuracy: 0.3732 - loss: 2.6736 - val_accuracy: 0.4334 - val_loss: 1.7331
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 63ms/step - accuracy: 0.4502 - loss: 1.8348 - val_accuracy: 0.3894 - val_loss: 2.6037
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.4882 - loss: 1.6132 - val_accuracy: 0.3764 - val_loss: 2.1506
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.5053 - loss: 1.5204 - val_accuracy: 0.4134 - val_loss: 3.2766
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.5260 - loss: 1.4485 - val_accuracy: 0.4224 - val_loss: 2.1474
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.5643 - loss: 1.2801 - val_accuracy: 0.4174 - val_loss: 2.2575
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 68ms/step - accuracy: 0.5918 - loss: 1.1852 - val_accuracy: 0.4194 - val_loss: 2.1220
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - accuracy: 0.6061 - loss: 1.1374 - val_accuracy: 0.4404 - val_loss: 1.8974
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.5948 - loss: 1.1780 - val_accuracy: 0.3934 - val_loss: 3.0563
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.6058 - loss: 1.1714 - val_accuracy: 0.5245 - val_loss: 1.3811

wandb: Agent Starting Run: xx4o74dc with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 60ms/step - accuracy: 0.4185 - loss: 1.3910 - val_accuracy: 0.4344 - val_loss: 1.2837
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.4897 - loss: 1.2529 - val_accuracy: 0.4434 - val_loss: 1.2720
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5150 - loss: 1.1970 - val_accuracy: 0.4525 - val_loss: 1.2750
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5330 - loss: 1.1566 - val_accuracy: 0.4815 - val_loss: 1.2533
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.5528 - loss: 1.1254 - val_accuracy: 0.4825 - val_loss: 1.2489
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5715 - loss: 1.0857 - val_accuracy: 0.5175 - val_loss: 1.2093
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5850 - loss: 1.0435 - val_accuracy: 0.5455 - val_loss: 1.1767
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 38s 152ms/step - accuracy: 0.6058 - loss: 1.0194 - val_accuracy: 0.5265 - val_loss: 1.1698
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 56ms/step - accuracy: 0.6221 - loss: 0.9757 - val_accuracy: 0.5255 - val_loss: 1.1797
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - accuracy: 0.6363 - loss: 0.9434 - val_accuracy: 0.5395 - val_loss: 1.1721

wandb: Agent Starting Run: a419l0nx with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 16
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 63ms/step - accuracy: 0.3324 - loss: 1.5148 - val_accuracy: 0.4154 - val_loss: 1.4171
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 58ms/step - accuracy: 0.4235 - loss: 1.3704 - val_accuracy: 0.4474 - val_loss: 1.3500
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 58ms/step - accuracy: 0.4582 - loss: 1.3148 - val_accuracy: 0.4615 - val_loss: 1.3140
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 15s 60ms/step - accuracy: 0.4752 - loss: 1.2778 - val_accuracy: 0.4655 - val_loss: 1.2877
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 15s 59ms/step - accuracy: 0.4935 - loss: 1.2475 - val_accuracy: 0.4785 - val_loss: 1.2662
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5035 - loss: 1.2225 - val_accuracy: 0.4985 - val_loss: 1.2503
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5120 - loss: 1.2006 - val_accuracy: 0.5025 - val_loss: 1.2367
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 57ms/step - accuracy: 0.5225 - loss: 1.1811 - val_accuracy: 0.5025 - val_loss: 1.2259
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 50s 201ms/step - accuracy: 0.5335 - loss: 1.1632 - val_accuracy: 0.5125 - val_loss: 1.2147
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 14s 55ms/step - accuracy: 0.5410 - loss: 1.1473 - val_accuracy: 0.5165 - val_loss: 1.2058

wandb: Agent Starting Run: 3re5c81y with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 68ms/step - accuracy: 0.3499 - loss: 13.7130 - val_accuracy: 0.3443 - val_loss: 15.7657
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 62ms/step - accuracy: 0.4052 - loss: 6.1683 - val_accuracy: 0.4284 - val_loss: 2.4564
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 66ms/step - accuracy: 0.4352 - loss: 3.9809 - val_accuracy: 0.2903 - val_loss: 8.6309
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 19s 62ms/step - accuracy: 0.3837 - loss: 2.1274 - val_accuracy: 0.3483 - val_loss: 1.5026
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.3977 - loss: 1.3703 - val_accuracy: 0.3644 - val_loss: 1.4265
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.3934 - loss: 1.3556 - val_accuracy: 0.2172 - val_loss: 1.5892
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 15s 60ms/step - accuracy: 0.2831 - loss: 1.5264 - val_accuracy: 0.3063 - val_loss: 1.6601
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 66ms/step - accuracy: 0.2694 - loss: 1.5366 - val_accuracy: 0.2613 - val_loss: 1.5783
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 17s 69ms/step - accuracy: 0.2796 - loss: 1.4989 - val_accuracy: 0.3083 - val_loss: 1.6817
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 64ms/step - accuracy: 0.2879 - loss: 1.5011 - val_accuracy: 0.2863 - val_loss: 1.8099

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 5ik1ee67 with config:
wandb: 	batch_size: 16
wandb: 	epochs: 10
wandb: 	hidden_nodes: 64
wandb: 	img_size: 224
wandb: 	learning_rate: 0.0001
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 18s 66ms/step - accuracy: 0.3927 - loss: 1.9291 - val_accuracy: 0.4645 - val_loss: 1.4144
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 63ms/step - accuracy: 0.4572 - loss: 1.6278 - val_accuracy: 0.4174 - val_loss: 2.1344
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.5053 - loss: 1.4713 - val_accuracy: 0.4024 - val_loss: 2.3361
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.5248 - loss: 1.3779 - val_accuracy: 0.4384 - val_loss: 2.1024
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.5623 - loss: 1.3097 - val_accuracy: 0.4575 - val_loss: 1.8553
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.5688 - loss: 1.2449 - val_accuracy: 0.4555 - val_loss: 1.7430
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 82s 329ms/step - accuracy: 0.5953 - loss: 1.1873 - val_accuracy: 0.4975 - val_loss: 1.7126
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.6088 - loss: 1.1258 - val_accuracy: 0.5035 - val_loss: 1.6489
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 15s 62ms/step - accuracy: 0.6181 - loss: 1.1205 - val_accuracy: 0.4464 - val_loss: 2.4027
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 16s 62ms/step - accuracy: 0.6303 - loss: 1.1041 - val_accuracy: 0.4424 - val_loss: 2.3138

wandb: Sweep Agent: Waiting for job.
wandb: Sweep Agent: Exiting.